#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import os
import re
import secrets
from html import unescape
from urllib.parse import unquote

from flask import Flask, make_response, render_template, request

app = Flask(__name__)


BLOCKLIST = [
    (r"<\s*/?\s*script\b", re.IGNORECASE),
    (r"<\s*/?\s*img\b", re.IGNORECASE),
    (r"<\s*/?\s*svg\b", re.IGNORECASE),
    (r"<\s*/?\s*iframe\b", re.IGNORECASE),
    (r"<\s*/?\s*input\b", re.IGNORECASE),
    (r"<\s*/?\s*object\b", re.IGNORECASE),
    (r"<\s*/?\s*applet\b", re.IGNORECASE),
    (r"<\s*/?\s*base\b", re.IGNORECASE),
    (r"<\s*/?\s*component\b", re.IGNORECASE),
    (r"<\s*/?\s*embed\b", re.IGNORECASE),
    (r"<\s*/?\s*frame\b", re.IGNORECASE),
    (r"<\s*/?\s*geolocation\b", re.IGNORECASE),
    (r"<\s*/?\s*math\b", re.IGNORECASE),
    (r"<\s*/?\s*meta\b", re.IGNORECASE),
    (r"<\s*/?\s*video\b", re.IGNORECASE),
    (r"<\s*/?\s*audio\b", re.IGNORECASE),
    (r"<\s*/?\s*source\b", re.IGNORECASE),
    (r"<\s*/?\s*track\b", re.IGNORECASE),
    (r"<\s*/?\s*html\b", re.IGNORECASE),
    (r"<\s*/?\s*body\b", re.IGNORECASE),
    (r"<\s*/?\s*frameset\b", re.IGNORECASE),
    (r"<\s*/?\s*details\b", re.IGNORECASE),
    (r"<\s*/?\s*dialog\b", re.IGNORECASE),
    (r"<\s*/?\s*marquee\b", re.IGNORECASE),
    (r"<\s*/?\s*style\b", re.IGNORECASE),
    (r"<\s*/?\s*link\b", re.IGNORECASE),
    (r"<\s*/?\s*template\b", re.IGNORECASE),
    (r"onafterprint", re.IGNORECASE),
    (r"onanimationcancel", re.IGNORECASE),
    (r"onanimationend", re.IGNORECASE),
    (r"onanimationiteration", re.IGNORECASE),
    (r"onanimationstart", re.IGNORECASE),
    (r"onauxclick", re.IGNORECASE),
    (r"onbeforecopy", re.IGNORECASE),
    (r"onbeforecut", re.IGNORECASE),
    (r"onbeforeinput", re.IGNORECASE),
    (r"onbeforematch", re.IGNORECASE),
    (r"onbeforepaste", re.IGNORECASE),
    (r"onbeforeprint", re.IGNORECASE),
    (r"onbeforetoggle", re.IGNORECASE),
    (r"onbeforeunload", re.IGNORECASE),
    (r"onbegin", re.IGNORECASE),
    (r"onblur", re.IGNORECASE),
    (r"onbounce", re.IGNORECASE),
    (r"oncancel", re.IGNORECASE),
    (r"oncanplay", re.IGNORECASE),
    (r"oncanplaythrough", re.IGNORECASE),
    (r"onchange", re.IGNORECASE),
    (r"onclick", re.IGNORECASE),
    (r"onclose", re.IGNORECASE),
    (r"oncommand", re.IGNORECASE),
    (r"oncontentvisibilityautostatechange", re.IGNORECASE),
    (r"oncontextmenu", re.IGNORECASE),
    (r"oncopy", re.IGNORECASE),
    (r"oncuechange", re.IGNORECASE),
    (r"oncut", re.IGNORECASE),
    (r"ondevicemotion", re.IGNORECASE),
    (r"ondeviceorientation", re.IGNORECASE),
    (r"ondeviceorientationabsolute", re.IGNORECASE),
    (r"ondblclick", re.IGNORECASE),
    (r"ondrag", re.IGNORECASE),
    (r"ondragend", re.IGNORECASE),
    (r"ondragenter", re.IGNORECASE),
    (r"ondragexit", re.IGNORECASE),
    (r"ondragleave", re.IGNORECASE),
    (r"ondragover", re.IGNORECASE),
    (r"ondragstart", re.IGNORECASE),
    (r"ondrop", re.IGNORECASE),
    (r"ondurationchange", re.IGNORECASE),
    (r"onend", re.IGNORECASE),
    (r"onended", re.IGNORECASE),
    (r"onerror", re.IGNORECASE),
    (r"onfinish", re.IGNORECASE),
    (r"onfocus", re.IGNORECASE),
    (r"onfocusin", re.IGNORECASE),
    (r"onfocusout", re.IGNORECASE),
    (r"onformdata", re.IGNORECASE),
    (r"onfullscreenchange", re.IGNORECASE),
    (r"ongesturechange", re.IGNORECASE),
    (r"ongestureend", re.IGNORECASE),
    (r"ongesturestart", re.IGNORECASE),
    (r"ongotpointercapture", re.IGNORECASE),
    (r"onhashchange", re.IGNORECASE),
    (r"oninput", re.IGNORECASE),
    (r"oninvalid", re.IGNORECASE),
    (r"onkeydown", re.IGNORECASE),
    (r"onkeypress", re.IGNORECASE),
    (r"onkeyup", re.IGNORECASE),
    (r"onload", re.IGNORECASE),
    (r"onloadeddata", re.IGNORECASE),
    (r"onloadend", re.IGNORECASE),
    (r"onloadedmetadata", re.IGNORECASE),
    (r"onloadstart", re.IGNORECASE),
    (r"onlocation", re.IGNORECASE),
    (r"onlostpointercapture", re.IGNORECASE),
    (r"onmessage", re.IGNORECASE),
    (r"onmousedown", re.IGNORECASE),
    (r"onmouseenter", re.IGNORECASE),
    (r"onmouseleave", re.IGNORECASE),
    (r"onmousemove", re.IGNORECASE),
    (r"onmouseout", re.IGNORECASE),
    (r"onmouseover", re.IGNORECASE),
    (r"onmouseup", re.IGNORECASE),
    (r"onmousewheel", re.IGNORECASE),
    (r"onmozfullscreenchange", re.IGNORECASE),
    (r"onpagehide", re.IGNORECASE),
    (r"onpagereveal", re.IGNORECASE),
    (r"onpageshow", re.IGNORECASE),
    (r"onpageswap", re.IGNORECASE),
    (r"onpaste", re.IGNORECASE),
    (r"onpause", re.IGNORECASE),
    (r"onplay", re.IGNORECASE),
    (r"onplaying", re.IGNORECASE),
    (r"onpointercancel", re.IGNORECASE),
    (r"onpointerdown", re.IGNORECASE),
    (r"onpointerenter", re.IGNORECASE),
    (r"onpointerleave", re.IGNORECASE),
    (r"onpointermove", re.IGNORECASE),
    (r"onpointerout", re.IGNORECASE),
    (r"onpointerover", re.IGNORECASE),
    (r"onpointerrawupdate", re.IGNORECASE),
    (r"onpointerup", re.IGNORECASE),
    (r"onpopstate", re.IGNORECASE),
    (r"onprogress", re.IGNORECASE),
    (r"onpromptaction", re.IGNORECASE),
    (r"onpromptdismiss", re.IGNORECASE),
    (r"onratechange", re.IGNORECASE),
    (r"onrepeat", re.IGNORECASE),
    (r"onreset", re.IGNORECASE),
    (r"onresize", re.IGNORECASE),
    (r"onscrollend", re.IGNORECASE),
    (r"onscrollsnapchange", re.IGNORECASE),
    (r"onscrollsnapchanging", re.IGNORECASE),
    (r"onsearch", re.IGNORECASE),
    (r"onsecuritypolicyviolation", re.IGNORECASE),
    (r"onseeked", re.IGNORECASE),
    (r"onseeking", re.IGNORECASE),
    (r"onselect", re.IGNORECASE),
    (r"onselectionchange", re.IGNORECASE),
    (r"onselectstart", re.IGNORECASE),
    (r"onshow", re.IGNORECASE),
    (r"onslotchange", re.IGNORECASE),
    (r"onstart", re.IGNORECASE),
    (r"onsubmit", re.IGNORECASE),
    (r"onsuspend", re.IGNORECASE),
    (r"ontimeupdate", re.IGNORECASE),
    (r"ontoggle", re.IGNORECASE),
    (r"ontouchcancel", re.IGNORECASE),
    (r"ontouchend", re.IGNORECASE),
    (r"ontouchmove", re.IGNORECASE),
    (r"ontouchstart", re.IGNORECASE),
    (r"ontransitioncancel", re.IGNORECASE),
    (r"ontransitionend", re.IGNORECASE),
    (r"ontransitionrun", re.IGNORECASE),
    (r"ontransitionstart", re.IGNORECASE),
    (r"onunhandledrejection", re.IGNORECASE),
    (r"onunload", re.IGNORECASE),
    (r"onvalidationstatuschange", re.IGNORECASE),
    (r"onvolumechange", re.IGNORECASE),
    (r"onwaiting", re.IGNORECASE),
    (r"onwebkitanimationend", re.IGNORECASE),
    (r"onwebkitanimationiteration", re.IGNORECASE),
    (r"onwebkitanimationstart", re.IGNORECASE),
    (r"onwebkitfullscreenchange", re.IGNORECASE),
    (r"onwebkitmouseforcechanged", re.IGNORECASE),
    (r"onwebkitmouseforcedown", re.IGNORECASE),
    (r"onwebkitmouseforceup", re.IGNORECASE),
    (r"onwebkitmouseforcewillbegin", re.IGNORECASE),
    (r"onwebkitneedkey", re.IGNORECASE),
    (r"onwebkitplaybacktargetavailabilitychanged", re.IGNORECASE),
    (r"onwebkitpresentationmodechanged", re.IGNORECASE),
    (r"onwebkittransitionend", re.IGNORECASE),
    (r"onwebkitwillrevealbottom", re.IGNORECASE),
    (r"onwheel", re.IGNORECASE),
    (r"autofocus", re.IGNORECASE),
    (r"style", re.IGNORECASE),
    (r"animation", re.IGNORECASE),
    (r"keyframes", re.IGNORECASE),
    (r"content-?visibility", re.IGNORECASE),
    (r"transition", re.IGNORECASE),
    (r"transform", re.IGNORECASE),
    (r"shadow", re.IGNORECASE),
    (r"slot", re.IGNORECASE),
    (r"fetch", re.IGNORECASE),
    (r"xmlhttprequest", re.IGNORECASE),
    (r"sendbeacon", re.IGNORECASE),
    (r"location", re.IGNORECASE),
    (r"open\s*\(", re.IGNORECASE),
    (r"assign\s*\(", re.IGNORECASE),
    (r"replace\s*\(", re.IGNORECASE),
    (r"pushstate", re.IGNORECASE),
    (r"replacestate", re.IGNORECASE),
    (r"submit", re.IGNORECASE),
    (r"requestsubmit", re.IGNORECASE),
    (r"click", re.IGNORECASE),
    (r"createelement(?:ns)?", re.IGNORECASE),
    (r"(?:adopt|import|clone)node", re.IGNORECASE),
    (r"append(?:child)?", re.IGNORECASE),
    (r"prepend", re.IGNORECASE),
    (r"before", re.IGNORECASE),
    (r"after", re.IGNORECASE),
    (r"insertbefore", re.IGNORECASE),
    (r"insertadjacent(?:html|text|element)", re.IGNORECASE),
    (r"replace(?:children|child|with)", re.IGNORECASE),
    (r"remove(?:child)?", re.IGNORECASE),
    (r"innerhtml", re.IGNORECASE),
    (r"outerhtml", re.IGNORECASE),
    (r"(?:inner|outer)(?:text|html)", re.IGNORECASE),
    (r"textcontent", re.IGNORECASE),
    (r"setattribute(?:ns)?", re.IGNORECASE),
    (r"removeattribute(?:ns)?", re.IGNORECASE),
    (r"toggleattribute", re.IGNORECASE),
    (r"queryselector(?:all)?", re.IGNORECASE),
    (r"getelement(?:sbytagname|sbyclassname|byid|sbyname)", re.IGNORECASE),
    (r"write", re.IGNORECASE),
    (r"writeln", re.IGNORECASE),
    (r"href", re.IGNORECASE),
    (r"src", re.IGNORECASE),
    (r"action", re.IGNORECASE),
    (r"formaction", re.IGNORECASE),
    (r"srcdoc", re.IGNORECASE),
    (r"cookiestore", re.IGNORECASE),
    (r"cookie", re.IGNORECASE),
    (r"(?:local|session)storage", re.IGNORECASE),
    (r"formdata", re.IGNORECASE),
    (r"url(?:searchparams)?", re.IGNORECASE),
    (r"request", re.IGNORECASE),
    (r"headers", re.IGNORECASE),
    (r"response", re.IGNORECASE),
    (r"media", re.IGNORECASE),
    (r"image", re.IGNORECASE),
    (r"audio", re.IGNORECASE),
    (r"video", re.IGNORECASE),
    (r"track", re.IGNORECASE),
    (r"source", re.IGNORECASE),
    (r"bitmap", re.IGNORECASE),
    (r"canvas", re.IGNORECASE),
    (r"blob", re.IGNORECASE),
    (r"file", re.IGNORECASE),
    (r"navigator", re.IGNORECASE),
    (r"geolocation", re.IGNORECASE),
    (r"postmessage", re.IGNORECASE),
    (r"document", re.IGNORECASE),
    (r"window", re.IGNORECASE),
    (r"globalthis", re.IGNORECASE),
    (r"global", re.IGNORECASE),
    (r"self", re.IGNORECASE),
    (r"this", re.IGNORECASE),
    (r"top", re.IGNORECASE),
    (r"parent", re.IGNORECASE),
    (r"frames", re.IGNORECASE),
    (r"form", re.IGNORECASE),
    (r"element", re.IGNORECASE),
    (r"eval", re.IGNORECASE),
    (r"function", re.IGNORECASE),
    (r"constructor", re.IGNORECASE),
    (r"set(?:timeout|interval)", re.IGNORECASE),
    (r"alert\s*[\(`]", re.IGNORECASE),
    (r"confirm\s*[\(`]", re.IGNORECASE),
    (r"prompt\s*[\(`]", re.IGNORECASE),
    (r"print\s*[\(`]", re.IGNORECASE),
    (r"navigation", re.IGNORECASE),
    (
        r"j[\x00-\x20]*a[\x00-\x20]*v[\x00-\x20]*a[\x00-\x20]*s"
        r"[\x00-\x20]*c[\x00-\x20]*r[\x00-\x20]*i[\x00-\x20]*p"
        r"[\x00-\x20]*t[\x00-\x20]*:",
        re.IGNORECASE,
    ),
    (r"import", re.IGNORECASE),
]


_JS_BRACED_ESCAPE = re.compile(r"\\u\{([0-9a-fA-F]+)\}")
_JS_FIXED_ESCAPE = re.compile(r"\\u([0-9a-fA-F]{4})")
_JS_HEX_ESCAPE = re.compile(r"\\x([0-9a-fA-F]{2})")
_JS_OCTAL_ESCAPE = re.compile(r"\\([0-7]{1,3})")
_JS_SIMPLE_ESCAPE = re.compile(r"\\([bfnrtv])")
_JS_LINE_CONTINUATION = re.compile(r"\\(?:\r\n|[\n\r\u2028\u2029])")
_JS_IDENTITY_ESCAPE = re.compile(r"\\(.)", re.DOTALL)


def _decode_js_escapes(value):
    def codepoint(match):
        try:
            return chr(int(match.group(1), 16))
        except (ValueError, OverflowError):
            return match.group(0)

    def octal(match):
        try:
            return chr(int(match.group(1), 8))
        except (ValueError, OverflowError):
            return match.group(0)

    def simple(match):
        return {
            "b": "\b",
            "f": "\f",
            "n": "\n",
            "r": "\r",
            "t": "\t",
            "v": "\v",
        }[match.group(1)]

    decoded = _JS_BRACED_ESCAPE.sub(codepoint, value)
    decoded = _JS_FIXED_ESCAPE.sub(codepoint, decoded)
    decoded = _JS_HEX_ESCAPE.sub(codepoint, decoded)
    decoded = _JS_OCTAL_ESCAPE.sub(octal, decoded)
    decoded = _JS_SIMPLE_ESCAPE.sub(simple, decoded)
    decoded = _JS_LINE_CONTINUATION.sub("", decoded)
    return _JS_IDENTITY_ESCAPE.sub(r"\1", decoded)


def _normalize(value):
    previous = None
    while value != previous:
        previous = value
        value = unquote(unescape(value)).replace("\x00", "")
        value = _decode_js_escapes(value)
    return value


def is_banned(value):
    normalized = _normalize(value)
    return any(
        re.search(pattern, normalized, flags=flags) for pattern, flags in BLOCKLIST
    )


@app.route("/", methods=["GET"])
def index():
    msg = request.args.get("msg")
    banned = bool(msg and is_banned(msg))
    csp_nonce = secrets.token_urlsafe(16)

    response = make_response(
        render_template(
            "index.html",
            msg=msg,
            banned=banned,
            csp_nonce=csp_nonce,
            share_url=request.url if msg else "",
        )
    )
    response.headers["Content-Security-Policy"] = (
        f"style-src 'self' https://cdn.internal 'nonce-{csp_nonce}'; style-src-attr 'none'"
    )
    return response


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
